### ISSUE TITLE
[Request] Sync discord rank to minecraft server 

### ISSUE THREAD

**Issue by DaFray31** [StaticFX/DiscordBotBungee#2]
Hello,
Will it be possible to make it sync the Discord ranks to the minecraft server ?
Regards,
DaFray31

**Comment by StaticFX** [comment]
So you mean when you get an discord rang it should sync up with the server? The problem with that is, that there are multiply permission system, and you have a lot of options on how to add groups. There is nothing like vault for bungeecord. Maybe a LuckPerms integration, but i can't think of any other solution.
