### ISSUE TITLE
SQL Error

### ISSUE THREAD

**Issue by jaceee** [StaticFX/DiscordBotBungee#3]
When you updated to version 1.2.0 (still present in 1.2.1) you took out the column Rank from the query but still keep sending the argument, so the driver sends an exception for sending 5 arguments for 4 params.

This is the specific line:
https://github.com/StaticFX/DiscordBotBungee/blob/5fbc5b3a8b502171f2ddb5df77af3ba4fe45a094/src/main/java/de/staticred/discordbot/db/VerifyDAO.java#L75

I would submit a pull request but I dont know how to compile this to test it, if you can guide me I can help with it.

**Comment by StaticFX** [comment]
Hey, fixxed your issue in the newest release. Thanks for reporting it :)
